import SideBar from "./components/SideBar";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { getServerSession } from "next-auth/next";
import { SessionProvider } from "./components/SessionProvider";
import ClientProvider from "./components/ClientProvider";
import Login from "./components/Login";
import { authOptions } from "@/pages/api/auth/[...nextauth]";
import { GlobalContextProvider } from "./context/store";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Chatbox Scada",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider session={session}>
          {/* ClientProvider - Notification */}
          <ClientProvider />
          {!session ? (
            <Login />
          ) : (
            <GlobalContextProvider>
              <div className="flex">
                {/* Sidebar */}
                {session && <SideBar />}
                <div className="bg-[#343541] flex-1">{children}</div>
              </div>
            </GlobalContextProvider>
          )}
        </SessionProvider>
      </body>
    </html>
  );
}
